POST http://localhost:8080/api/products
Content-Type: application/json
Accept: application/json

{
    "name": "Kopi Susu Gula Aren",
    "price": 20000,
    "stock": 10
}

###
GET http://localhost:8080/api/products
Accept: application/json

###
@PRODUCT_ID = 872fc24d-0aab-4d37-ae08-b40e41c03f2e

###
GET http://localhost:8080/api/products/{{PRODUCT_ID}}
Accept: application/json

###
PUT http://localhost:8080/api/products/{{PRODUCT_ID}}
Content-Type: application/json
Accept: application/json

{
    "name": "Oat Milk Latte",
    "price": 24000,
    "stock": 10
}

###
DELETE http://localhost:8080/api/products/{{PRODUCT_ID}}
Accept: application/json
