-- 001_products.sql
CREATE TABLE IF NOT EXISTS products (
	id UUID PRIMARY KEY,
	name TEXT NOT NULL,
	price BIGINT NOT NULL,
	stock INTEGER NOT NULL,

	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

	deleted_at TIMESTAMPTZ,
	is_active BOOLEAN NOT NULL DEFAULT TRUE
);

