-- 001_products.sql
CREATE TABLE IF NOT EXISTS products (
	id TEXT PRIMARY KEY,
	name TEXT NOT NULL,
	price INTEGER NOT NULL,
	stock INTEGER NOT NULL,

	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

	deleted_at TIMESTAMPTZ,
	is_active BOOLEAN NOT NULL DEFAULT TRUE
);

