-- 001_products.sql
CREATE TABLE IF NOT EXISTS products (
	id TEXT PRIMARY KEY,
	name TEXT NOT NULL,
	price INTEGER NOT NULL,
	stock INTEGER NOT NULL,

	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

	deleted_at DATETIME DEFAULT NULL,
	is_active BOOLEAN NOT NULL DEFAULT 1
);
