### Create
POST http://localhost:8080/api/categories
Content-Type: application/json
Accept: application/json

{
    "name": "Kopi 2",
    "description": "Berisi kopi-kopi pilihan."
}

### Read All
GET http://localhost:8080/api/categories
Accept: application/json

###
@CATEGORY_ID = c4a45d54-bdc6-4783-91db-3acf9fcf415b

### Read One
GET http://localhost:8080/api/categories/{{CATEGORY_ID}}
Accept: application/json

### Update
PUT http://localhost:8080/api/categories/{{CATEGORY_ID}}
Content-Type: application/json
Accept: application/json

{
    "name": "Kopi",
    "description": "Berisi kopi"
}

### Delete
DELETE http://localhost:8080/api/categories/{{CATEGORY_ID}}
Accept: application/json
