### ENV
@CATEGORY_ID = abf77a4a-0fec-4760-be10-3e8f929cccfe
@PRODUCT_ID = d03e36df-9b61-4aed-acc3-73c4180b9280


### Create
POST http://localhost:8080/api/products
Content-Type: application/json
Accept: application/json

{
    "name": "Kopi Susu Gula Aren",
    "price": 20000,
    "stock": 10,
    "category_id": "{{CATEGORY_ID}}"
}

###
GET http://localhost:8080/api/products?query=kopi&page=1&limit=10
Accept: application/json

###
GET http://localhost:8080/api/products/{{PRODUCT_ID}}
Accept: application/json

###
PUT http://localhost:8080/api/products/{{PRODUCT_ID}}
Content-Type: application/json
Accept: application/json

{
    "name": "Oat Milk Latte",
    "price": 24000,
    "stock": 10,
    "category_id": "{{CATEGORY_ID}}"
}

###
DELETE http://localhost:8080/api/products/{{PRODUCT_ID}}
Accept: application/json
