### ENV
@PRODUCT_ID = 7c2a716d-1e0a-4a9e-9e64-dc575e3c1f20


POST http://localhost:8080/api/transactions/checkout
Content-Type: application/json
Accept: application/json

{
    "items": [
        {
            "product_id": "{{PRODUCT_ID}}",
            "quantity": 1
        }
    ]
}

### Checkout (Validation Error - Empty Items)
POST http://localhost:8080/api/transactions/checkout
Content-Type: application/json
Accept: application/json

{
    "items": []
}

### Checkout (Validation Error - Invalid Quantity)
POST http://localhost:8080/api/transactions/checkout
Content-Type: application/json
Accept: application/json

{
    "items": [
        {
            "product_id": "{{PRODUCT_ID}}",
            "quantity": 0
        },
        {
            "product_id": "{{PRODUCT_ID}}",
            "quantity": 2
        }
    ]
}

### Get Report Today
GET http://localhost:8080/api/report/hari-ini
Accept: application/json

### Get Report Custom Range
GET http://localhost:8080/api/report?start_date=2026-01-01&end_date=2026-03-01
Accept: application/json